### ISSUE TITLE
Playing flv files

### ISSUE THREAD

**Issue by greenpdx** [MoePlayer/vue-dplayer#13]
I am trying to play flv files. I get "This video fails to load". I look at the network in Chrome debugger and I see 1M out of 86M transferred. 
I am using nginx as a web server. In the log file I see a transfer of a partial video ( status 206 )  

Here is a partial code of the HTML and imports.

What am I doing wrong?

```
  <div class="video">
    <div class="player">
      <d-player
        ref="player"
        :video="playerOptions.video"
        :preload="playerOptions.preload"
        :autoplay="playerOptions.autoplay"
        :contextmenu="playerOptions.contextmenu"
        :lang="playerOptions.lang"
        @play="onPlayerPlay($event)"
        @pause="onPlayerPause($event)"
        @ended="onPlayerEnded($event)"
        @playing="onPlayerPlaying($event)"
        @canplay="onPlayerCanplay($event)"
        @error="playerError($event)">
      </d-player>
    </div>
  </div>
</template>

<script>
// import Vue from 'vue'
import 'flv.js'
import 'hls.js'
import VueDPlayer from 'vue-dplayer'

export default {
  name: 'PlayVid',
  components: {
    'd-player': VueDPlayer
  },
```

**Comment by matthewton** [comment]
have you solved your problem? I got the same when trying to use use flv.js
No idea how to combine flv.js into it!

**Comment by matthewton** [comment]
@greenpdx, have you solved your problem? I got the same when trying to use use flv.js
No idea how to combine flv.js into it!

**Comment by sinchang** [comment]
@matthewton 

try

```
import flvjs from 'flv.js'

window.flvjs = flvjs
```

**Comment by sinchang** [comment]
ref: https://github.com/Bilibili/flv.js/issues/47

**Comment by gy95** [comment]
@sinchang 
1. Access to fetch at 'https://xxxxxxxx/77635333.flv' from origin 'http://localhost:9528' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 

2.[IOController] > Loader error, code = -1, msg = Failed to fetch

3.[TransmuxingController] > IOException: type = Exception, code = -1, msg = Failed to fetch

4.Uncaught (in promise) Error: Uncaught, unspecified "error" event. (NetworkError)
    at EventEmitter../node_modules/_events@1.1.1@events/events.js.EventEmitter.emit (events.js:62)
    at EventEmitter._transmuxer.on (flv-player.js:236)
    at EventEmitter../node_modules/_events@1.1.1@events/events.js.EventEmitter.emit (events.js:84)
    at Promise.resolve.then (transmuxer.js:175)

**above are 4 errors, what is the reason? but i use 'https://3333.mp4' , a mp4 file, and  there is no err. why?**
