### ISSUE TITLE
lang: 'en' does not work ..

### ISSUE THREAD

**Issue by erwin16** [MoePlayer/vue-dplayer#16]
here is my data

        video: {
        url: 'http://localhost:8080/static/video/choro.mp4',
        pic: 'http://localhost:8080/static/pictures/choro.jpg'
      },
      autoplay: false,
      theme: '#FADFA3',
      lang: 'en',
      screenshot: true,
      player: null,
      contextmenu: [
        {
          text: 'Facebook',
          link: 'https://www.facebook.com/chorodescharentes/'
        }
      ]

but I still get settngs in chinese ...

**Comment by sinchang** [comment]
please update version to 0.0.4

**Comment by erwin16** [comment]
thanks a lot ...
Tell me which string translation you need if you ant to add french as a new language ( 'fr' )

**Comment by sinchang** [comment]
recommend you send a pull request to DPlayer repo. https://github.com/MoePlayer/DPlayer/blob/master/src/js/i18n.js

**Comment by erwin16** [comment]
cannot install correctly v0.0.4

  yarn add vue-dplayer

in node-modules / vue-dplayer , there is NO dist. and src /. onmy node_modules/ and package.json

**Comment by sinchang** [comment]
sorry use 0.0.5

**Comment by erwin16** [comment]
done ! thanks working fine....  enjoy your day !
your component is used in my  hello-vue sandbox .. 

[https://github.com/erwin16/hello-vue](url)
