### ISSUE TITLE
Duplicated __$$styleInject

### ISSUE THREAD

**Issue by egoist** [MoePlayer/vue-dplayer#18]
See https://github.com/MoePlayer/vue-dplayer/blob/master/dist/vue-dplayer.cjs.js

`bili` already ships `rollup-plugin-postcss` so you don't need to add it here https://github.com/MoePlayer/vue-dplayer/blob/master/bili.config.js#L4 which would make `__$$styleInject` function duplicated.

**Comment by sinchang** [comment]
![wx20180125-222432](https://user-images.githubusercontent.com/3297859/35392956-86342ebc-021e-11e8-9f14-69e000da7b15.png)

when removing line 4, file build failure, work fine added.

**Comment by egoist** [comment]
Just fixed here https://github.com/egoist/bili/commit/dea7ef65c7d64ff77773b1b2e9d7d846cf738986

**Comment by sinchang** [comment]
good job. waiting for you releasing the new version.

**Comment by egoist** [comment]
Done: https://github.com/egoist/bili/releases/tag/v2.0.0

There's a breaking change too

**Comment by egoist** [comment]
btw it's always better to extract css to reduce the size of js file and make browser parse js faster.
