### ISSUE TITLE
使用了你的dist中的vue-dplayer.js，请问怎么注册Vue.use

### ISSUE THREAD

**Issue by Panhaiwei** [MoePlayer/vue-dplayer#19]
如题，，，怎么Vue.use(????)...

页面中是使用script导入的

**Comment by sinchang** [comment]
supported in v0.0.9

demo: http://codepan.net/gist/f53d66eddf4fa14b4d26b7e05daaa914

**Comment by Panhaiwei** [comment]
已解决 谢谢 @sinchang
