### ISSUE TITLE
加载弹幕时，控制台报错 "TypeError: Cannot read property 'style' of null"

### ISSUE THREAD

**Issue by lemos1235** [MoePlayer/vue-dplayer#20]
![image](https://user-images.githubusercontent.com/23135552/35906404-5250989a-0c25-11e8-800e-130a2e5d6571.png)

**Comment by sinchang** [comment]
请附上重现链接 codepen 或者 jsfiddle.net

**Comment by lemos1235** [comment]
问题解决了。上面那个错误是option没有预先定义。后面我看了下源码，切换弹幕属性（not required）时，这块没有作非空处理。
![image](https://user-images.githubusercontent.com/23135552/35914985-407c6110-0c40-11e8-81a3-c0d7c8d87361.png)
