### ISSUE TITLE
contextmenu无效，

### ISSUE THREAD

**Issue by shaonq** [MoePlayer/vue-dplayer#5]
```
data() {
      return {
        video: {
          url: 'http://static.smartisanos.cn/common/video/t1-ui.mp4',
          pic: 'http://static.smartisanos.cn/pr/img/video/video_03_cc87ce5bdb.jpg'
        },
        autoplay: false,
        contextmenu: [
          {
            text: 'about',
            link: 'https://github.com/DIYgod/DPlayer'
          },
        ]
      }
    }
```

**Comment by sinchang** [comment]
dplayer 版本问题，周末有空升级下版本。

**Comment by cnlinjie** [comment]
您源码里面没有设置 contextmenu 啊~，
 const player = this.dp = new DPlayer({
                element: this.$el,
                autoplay: this.autoplay,
                theme: this.theme,
                loop: this.loop,
                lang: this.lang,
                screenshot: this.screenshot,
                hotkey: this.hotkey,
                preload: this.preload,
                video: {
                    url: this.video.url,
                    pic: this.video.pic,
                    type: 'normal'
                }
            })

**Comment by sinchang** [comment]
现在依赖的版本是  "dplayer": "^1.1.4"，所以不支持，后期升级下 dplayer 版本就可以了。

**Comment by cnlinjie** [comment]
@sinchang  感谢。
我这边先自己加一下，比较急。
