### ISSUE TITLE
demo是无效链接，请问demo能详细一点吗？

### ISSUE THREAD

**Issue by OBKoro1** [MoePlayer/vue-dplayer#6]

**Comment by sinchang** [comment]
readme 的 demo url  忘记改了，正常的是 http://dplayer.surge.sh/。

**Comment by OBKoro1** [comment]
大佬，有demo的源码吗，想看看具体实现过程。大佬可以发个邮件过来吗，感激不尽。邮箱：obkoro1@foxmail.com

**Comment by DIYgod** [comment]
https://github.com/MoePlayer/vue-dplayer/tree/gh-pages

**Comment by OBKoro1** [comment]
咦，这个是压缩的。。。

**Comment by sinchang** [comment]
https://github.com/MoePlayer/vue-dplayer/tree/master/example

**Comment by OBKoro1** [comment]
好的，谢谢大佬。
