### ISSUE TITLE
Support hls

### ISSUE THREAD

**Issue by chuangtim** [MoePlayer/vue-dplayer#9]
Hi. how to import hls.js? I try any way but can`t work. please help!!

**Comment by Oukanina** [comment]
@chuangtim  Hi, how did your import hls.js?

**Comment by SongChao1123** [comment]
require('videojs-contrib-hls/dist/videojs-contrib-hls'); 
It doesn't work

**Comment by DIYgod** [comment]
Try this
```js
const Hls = require('videojs-contrib-hls');
```

**Comment by SongChao1123** [comment]
Thank you, that's it
